# Generated by Django 5.1.4 on 2025-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermetrics',
            name='server_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='servermetrics',
            unique_together={('server_id', 'timestamp')},
        ),
    ]
