# Generated by Django 5.1.4 on 2025-02-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_monitoring', '0002_alter_servermetrics_server_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servermetrics',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servermetrics',
            name='server_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
