# Generated by Django 5.1.4 on 2025-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_monitoring', '0004_alter_servermetrics_server_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermetrics',
            name='db_service_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='servermetrics',
            name='web_service_status',
            field=models.JSONField(default=dict),
        ),
    ]
