# Generated by Django 5.1.4 on 2025-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_monitoring', '0005_servermetrics_db_service_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermetrics',
            name='db_service_status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='servermetrics',
            name='web_service_status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
