# Generated by Django 5.1.4 on 2025-02-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_monitoring', '0006_alter_servermetrics_db_service_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermetrics',
            name='db_service_status',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='servermetrics',
            name='web_service_status',
            field=models.TextField(default='{}'),
        ),
    ]
